/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logina;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author javier
 */
public class ConsultaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaAlumno
     */
    public ConsultaAlumno() {
        initComponents();
        DefaultTableModel data = new DefaultTableModel(new String[]{"Carné", "Nombre", "Apellidos", "Password"}, LoginA.alumnos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Alumno e : LoginA.alumnos) {
            jTable1.setValueAt(e.carné, row, 0);
            jTable1.setValueAt(e.nombre, row, 1);
            jTable1.setValueAt(e.apellidos, row, 2);
            jTable1.setValueAt(e.password, row, 3);

            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Carga masiva XML");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar en Xml");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3)
                        .addGap(208, 208, 208)
                        .addComponent(jButton4)
                        .addGap(72, 72, 72)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Administrados a = new Administrados();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int seleccion = jTable1.getSelectedRow();
        if (seleccion != -1) {
            EdicionAlumno a = new EdicionAlumno(jTable1.getSelectedRow());
            a.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ninguna celda seleccionada");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this, "Cargar");
        if (retorno == JFileChooser.APPROVE_OPTION) {
            leerArchivoXml(archivo.getSelectedFile());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String contenido = "<alumnos>\n";

        for (Alumno e : LoginA.alumnos) {
            contenido += "\t<alumno>\n";
            contenido += "\t\t<carne>";
            contenido += e.carné;
            contenido += "</carne>\n";
            contenido += "\t\t<nombre>";
            contenido += e.nombre;
            contenido += "</nombre>\n";
            contenido += "\t\t<apellido>";
            contenido += e.apellidos;
            contenido += "</apellido>\n";
            contenido += "\t\t<password>";
            contenido += e.password;
            contenido += "</password>\n";
            contenido += "\t</alumno>\n";
        }

        contenido += "</alumnos>";
        JFileChooser archivo = new JFileChooser();
        int retorno = archivo.showDialog(this, "Cargar");
        if (retorno == JFileChooser.APPROVE_OPTION) {
            escribirArchivo(archivo.getSelectedFile().toPath().toString(), contenido);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    public void leerArchivoXml(File archivo) {
        try {
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            Document doc = db.parse(archivo);

            doc.getDocumentElement().normalize();
            NodeList nodos = doc.getElementsByTagName("alumno");

            for (int i = 0; i < nodos.getLength(); i++) {
                Node nodo = nodos.item(i);
                if (nodo.getNodeType() == Node.ELEMENT_NODE) {
                    Element e = (Element) nodo;
                    Alumno al = new Alumno();
                    al.carné = String.valueOf(e.getElementsByTagName("carne").item(0).getTextContent());
                    al.nombre = String.valueOf(e.getElementsByTagName("nombre").item(0).getTextContent());
                    al.apellidos = String.valueOf(e.getElementsByTagName("apellido").item(0).getTextContent());
                    al.password = String.valueOf(e.getElementsByTagName("password").item(0).getTextContent());
                    LoginA.alumnos.add(al);
                }
            }
            Actualizartabla();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Actualizartabla() {
        DefaultTableModel data = new DefaultTableModel(new String[]{"Carne", "Nombre", "Apellidos", "Password"}, LoginA.alumnos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Alumno e : LoginA.alumnos) {
            jTable1.setValueAt(e.carné, row, 0);
            jTable1.setValueAt(e.nombre, row, 1);
            jTable1.setValueAt(e.apellidos, row, 2);
            jTable1.setValueAt(e.password, row, 3);

            row++;
        }
    }
    
    public void escribirArchivo(String rutaConNombre, String contenido){
        try{
            FileWriter fw = new FileWriter(rutaConNombre);
            PrintWriter pw = new PrintWriter(fw);
            pw.write(contenido);
            pw.close();
            fw.close();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
